### ISSUE TITLE
Error fields aren't obvious or documented

### ISSUE THREAD

**Issue by grischard** [geofabrik/osmi_pubtrans3#6]
While some of these are comprehensible, I have no idea what some of the others are:

```
error_over_non_rail
error_over_rail
error_unordered_gap
error_wrong_structure
no_stops_pltf_at_begin
stoppltf_after_route
non_way_empty_role
stop_not_on_way
no_way_members
unknown_role
unknown_route_type
stop_is_not_node
```

**Comment by grischard** [comment]
I'll start documenting the ones I find.

`error_over_rail` means that a bus route goes over a way that's not recognised as either a valid highway type or a ferry. The valid highway types are: `living_street, motorway, motorway_link, pedestrian, primary, primary_link, residential, secondary, secondary_link, service, tertiary, tertiary_link, track, trunk, trunk_link, unclassified`. Note that `highway=construction` isn't accepted as a valid highway type even though it's not a railway like the error message would suggest.

https://github.com/geofabrik/osmi_pubtrans3/blob/master/src/route_writer.hpp#L31 has some comments, but to link them to error messages you have to do some guesswork and code digging.

**Comment by Nakaner** [comment]
Fixed by https://wiki.openstreetmap.org/w/index.php?title=OSM_Inspector%2FViews%2FPublic_Transport_-_Routes&type=revision&diff=1908998&oldid=1513793
