### ISSUE TITLE
Trolley wire is not required for trolley buses

### ISSUE THREAD

**Issue by urbalazs** [geofabrik/osmi_pubtrans3#9]
The new trolley buses can operate without trolley wire using the built-in battery. Due to this fact, no trolley wire is required in short distances. Please check [this area in Budapest, Hungary](https://tools.geofabrik.de/osmi/?view=pubtrans_routes&lon=19.05864&lat=47.49881&zoom=16&overlays=ptv2_routes_invalid,ptv2_error_,ptv2_error_ways,ptv2_error_nodes). This error report `error: trolley bus without trolley wire` cannot be fixed, because the road **has no trolley wire** at all. The trolley buses operates here by using battery.

I suggest to add an exception to the validator: if `trolley_wire=no` is mapped, no error message is displayed. Please add a hint in the error message to the mapper, how can they dismiss this kind of error by adding `trolley_wire=no`.

If there is a trolley bus route and no `trolley_wire=*` key is added, the error message should be still there.

**Comment by Nakaner** [comment]
resolved by https://github.com/geofabrik/osmi_pubtrans3/pull/11

**Comment by szjozsef** [comment]
Hello, something has changed in PT validator of  Geofabrik OSM Inspector, the route/road segments specially marked with trolley_wire=no is causing again errors for trolley route types: "trolley bus without trolley wire".
Until now this route types validated correctly on road segments marked specially with trolley_wire=no for segments where the trolley bus passed with alternative driving methods (battery based electric motors / hybrid (diesel or hydrogen) / etc..). This causing issue at least for me: [Brasov PT Trolley routes in city center without trolley wires](https://tools.geofabrik.de/osmi/?view=pubtrans_routes&lon=25.60317&lat=45.65200&zoom=15&baselayer=Geofabrik%20Standard&overlays=ptv2_routes_valid%2Cptv2_routes_invalid%2Cptv2_error_ways%2Cptv2_error_nodes%2Cptv2_routes_valid%2Cptv2_routes_invalid%2Cptv2_error_ways%2Cptv2_error_nodes)

**Comment by woodpeck** [comment]
Sorry, I have accidentally rolled out an old software version on the server which caused these false alerts. They will be gone by tomorrow.
